"""add total_size_bytes to projects

Revision ID: 813a0b2cbf6f
Revises: 81330966a144
Create Date: 2026-08-19 23:19:21.034910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '813a0b2cbf6f'
down_revision: Union[str, Sequence[str], None] = '81330966a144'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('total_size_bytes', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'total_size_bytes')
    # ### end Alembic commands ###
